### ISSUE TITLE
Pillow Issue

### ISSUE THREAD

**Issue by gewirtz** [PrincetonUniversity/install_pytorch#6]
I'm on Della, activated the torch-env, cloned this repo, but received the following error after trying python mnist_download.py:
Traceback (most recent call last):
  File "mnist_download.py", line 1, in <module>
    import torchvision
  File "/home/gewirtz/.conda/envs/torch-env/lib/python3.7/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/home/gewirtz/.conda/envs/torch-env/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/home/gewirtz/.conda/envs/torch-env/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/home/gewirtz/.conda/envs/torch-env/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/gewirtz/.conda/envs/torch-env/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/home/gewirtz/.conda/envs/torch-env/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/home/gewirtz/.conda/envs/torch-env/lib/python3.7/site-packages/PIL/__init__.py)

**Comment by hugovk** [comment]
There should be a fixed torchvision out this week (https://github.com/pytorch/vision/issues/1712#issuecomment-570286349), until then, the workaround is either to use the master version of torchvision (eg. `pip install -U git+https://github.com/pytorch/vision`), or Pillow<7 (eg. `pip install "pillow<7"`).

**Comment by gewirtz** [comment]
thanks!

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin

**Comment by dfan** [comment]
FYI this is no longer necessary if you use torchvision 0.4.2 :)
Pillow 7.1.0 added back the PILLOW_VERSION constant (albeit deprecated): https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html
