### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by jkq2015** [PrincetonUniversity/install_pytorch#7]
I'm on Adroit and installed GPU version Pytorch under the guidance of https://researchcomputing.princeton.edu/pytorch.
`$ module load anaconda3`
`$ conda create --name torch-env pytorch torchvision cudatoolkit=10.2 matplotlib tensorboard --channel pytorch`
`$ conda activate torch-env`

I cloned this repo and successfully ran `python download_mnist.py`. But after running `sbatch job.slurm`, I got the following error:
Traceback (most recent call last):
  File "mnist_classify.py", line 118, in <module>
    main()
  File "mnist_classify.py", line 111, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "mnist_classify.py", line 36, in train
    output = model(data)
  File "/home/kaiqij/.conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "mnist_classify.py", line 22, in forward
    x = F.relu(self.conv1(x))
  File "/home/kaiqij/.conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kaiqij/.conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/home/kaiqij/.conda/envs/torch-env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 349, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by jhalverson** [comment]
I suspect that you landed on the K40c node which is not compatible
with PyTorch 1.5. Trying modifying the Slurm script by requesting a
GPU in this way:

#SBATCH --gres=gpu:tesla_v100:1

Jon

**Comment by jkq2015** [comment]
Solved. Thanks!
